# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: Visual Studio Enterprise Subscription
  appName: DAVE

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(bcf07d27-4fc5-4514-87c3-66a67f62020c)'
    appType: 'functionAppLinux'
    appName: 'DAVE'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOCKER|microsoft/azure-functions-node8:2.0'