# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: Visual Studio Enterprise Subscription
  appName: mobigov-dave

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Listing Dirs.
    dir
  displayName: 'List folders'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'api'
    verbose: true
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run-script build'
    workingDir: 'api'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/api/lib' 
    includeRootFolder: true 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true
- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectedServiceName: 'AzureMobigov-conn'
    azureSubscription: $(Subscription)
    action: 'Create Or Update Resource Group'
    resourceGroupName: mobigov-dave
- task: AzureFunctionApp@1
  inputs:
    ConnectedServiceName: 'AzureMobigov-conn'
    azureSubscription: '$(Subscription)'
    appType: 'functionAppLinux'
    appName: 'mobigov-dave'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'