# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: 
  ## Add this under variables section in the pipeline
  appName: mobigov-dave

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  name: 'NPMInstall'
  inputs:
    command: 'install'
    workingDir: 'api'
    verbose: true
- task: Npm@1
  name: 'NPMBuild'
  inputs:
    command: 'custom'
    customCommand: 'run-script build'
    workingDir: 'api'
- task: CopyFiles@2
  name: 'CopyMain'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/api/node_modules/core-js'
    targetFolder: '$(Build.SourcesDirectory)/api/lib/main/core-js' 
- task: ArchiveFiles@2
  name: 'ArchiveMain'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/api/lib/main' 
    includeRootFolder: true 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true
- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectedServiceName: '$(SubscriptionConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: mobigov-dave
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/azure-deploy.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  name: "MekaFunction"
  inputs:
    ConnectedServiceName: '$(SubscriptionConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: mobigov-dave
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/ArmTemplates/FunctionTemplates/Meka/template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/ArmTemplates/FunctionTemplates/Meka/parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: meka_function_arm
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: '$(SubscriptionConnection)'
    appType: 'functionAppLinux'
    appName: 'meka'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'